language: bash

before_script:
    - sh extras/travis-ci/before_script.sh

script:
    - cd .. && cd ./lynis-sdk && sh lynis-devkit run unit-tests
    - cd ../lynis && find lynis include extras plugins -type f -exec shellcheck {} +

notifications:
  email:
    recipients:
      - lynis-dev@cisofy.com
    on_success: change
    on_failure: always
