Document: lynis
Title: Debian lynis Manual
Author: <insert document author here>
Abstract: This manual describes what lynis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lynis/lynis.sgml.gz

Format: postscript
Files: /usr/share/doc/lynis/lynis.ps.gz

Format: text
Files: /usr/share/doc/lynis/lynis.text.gz

Format: HTML
Index: /usr/share/doc/lynis/html/index.html
Files: /usr/share/doc/lynis/html/*.html
