#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen, CISOfy (michael.boelen@cisofy.com)
# Web site: https://cisofy.com
#
# This software is licensed under GPL, version 3. See LICENSE file for
# usage of this software.
#
#################################################################################
#
# Consts
#
#################################################################################
#

# Paths where system and program binaries are located
BINPATHS="/bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin \
          /usr/local/libexec /usr/libexec /usr/sfw/bin /usr/sfw/sbin \
          /usr/sfw/libexec /opt/sfw/bin /opt/sfw/sbin /opt/sfw/libexec \
          /usr/xpg4/bin /usr/css/bin /usr/ucb /usr/X11R6/bin /usr/X11R7/bin \
          /usr/pkg/bin /usr/pkg/sbin"

# Do not use specific language, fall back to default
# Some tools with translated strings are very hard to parse
unset LANG

#
#################################################################################
#
# Initialize defaults
#
#################################################################################
#
# == Variable initializing ==
#
    AUDITORNAME=""
    PROFILE=""
    REPORTFILE=""
    AFICKBINARY=""
    AIDEBINARY=""
    AASTATUSBINARY=""
    BINARY_SCAN_FINISHED=0
    CHECK_BINARIES=1
    CHKROOTKITBINARY=""
    CHKCONFIGBINARY=""
    CONTROL_URL_APPEND=""
    CONTROL_URL_PREPEND=""
    CUSTOM_URL_APPEND=""
    CUSTOM_URL_PREPEND=""
    DOCKER_DAEMON_RUNNING=0
    FILEVALUE=""
    FIND=""
    FIREWALL_ACTIVE=0
    FOUNDPATH=0
    GREPBINARY="grep"
    GRPCKBINARY=""
    GROUP_NAME=""
    HELPER=""
    HOSTID=""
    IPTABLESBINARY=""
    LINUX_VERSION=""
    LINUXCONFIGFILE=""
    LOGFILE=""
    LYNIS_COMPLIANCE_TESTS=0
    MACHINEID=""
    MALWARE_SCANNER_INSTALLED=0
    NGINX_ACCESS_LOG_DISABLED=0
    NGINX_ACCESS_LOG_MISSING=0
    NGINX_ALIAS_FOUND=0
    NGINX_ALLOW_FOUND=0
    NGINX_DENY_FOUND=0
    NGINX_ERROR_LOG_DEBUG=0
    NGINX_ERROR_LOG_MISSING=0
    NGINX_EXPIRES_FOUND=0
    NGINX_FASTCGI_FOUND=0
    NGINX_FASTCGI_PARAMS_FOUND=0
    NGINX_FASTCGI_PASS_FOUND=0
    NGINX_LISTEN_FOUND=0
    NGINX_LOCATION_FOUND=0
    NGINX_SSL_CIPHERS=0
    NGINX_SSL_ON=0
    NGINX_SSL_PREFER_SERVER_CIPHERS=0
    NGINX_SSL_PROTOCOLS=0
    NGINX_RETURN_FOUND=0
    NGINX_ROOT_FOUND=0
    OS=""; OS_MODE=""
    OS_REDHAT_OR_CLONE=0
    OSIRISBINARY=""
    PIDFILE=""
    PFFOUND=0
    PRIVILEGED=0
    PROFILEVALUE=""
    PSBINARY="ps"
    RKHUNTERBINARY=""
    RPMBINARY=""
    RUN_HELPERS=0
    RUN_PLUGINS=1
    RUN_TESTS=1
    SAMHAINBINARY=""
    SCAN_TEST_HEAVY=""; SCAN_TEST_MEDIUM=""; SCAN_TEST_LOW=""
    SESTATUSBINARY=""
    SERVICE_MANAGER=""
    SHOW_PROGRAM_DETAILS=1
    SHOW_REPORT=1
    SKIPPED_TESTS_ROOTONLY=""
    SSHKEYSCANBINARY=""
    SSHKEYSCANFOUND=0
    SYSLOGNGBINARY=""
    TEST_SKIP_ALWAYS=""
    TESTS_EXECUTED=""
    TESTS_SKIPPED=""
    TRIPWIREBINARY=""
    UPLOAD_OPTIONS=""
    UPDATE_CHECK_SKIPPED=0
    VALUE=""
    VMTYPE=""
#
#################################################################################
#
# * Options
#
#################################################################################
#
    CRONJOB=0                   # Run as a cronjob
    CTESTS_PERFORMED=0          # Number of tests which are performed
    DEBUG=0                     # Debugging mode (to screen)
    HPPOINTS=0                  # Number of hardening points
    HPTOTAL=0                   # Maximum number of hardening points
    LOG_INCORRECT_OS=1          # Log tests with incorrect OS
    NEVERBREAK=0                # Don't wait for user input
    PENTESTINGMODE=0            # Try tests without root privileges
    QUICKMODE=0                 # Don't wait for user input
    QUIET=0                     # Show normal messages and warnings as well
    SHOW_TOOL_TIPS=1            # Show inline tool tips (default true)
    SKIPLOGTEST=0               # Skip logging for one test
    SKIP_UPGRADE_TEST=0         # Skip upgrade test
    TESTS_TO_PERFORM=""         # Which tests only to perform
    TEST_PAUSE_TIME=0           # Default pause time
    TOTAL_TESTS=0               # Total amount of tests (counter)
    UPLOAD_DATA=0               # Upload of data to central node
    VIEWHELP=0                  # Show help
    WRONGOPTION=0               # A wrong option is used
#
#################################################################################
#
    # Installed packages and other settings
    COMPILER_INSTALLED=0
#
#################################################################################
#
# * Colors
#
# For improved display
#
#################################################################################
#
    NORMAL="[0;39m"
    WARNING="[1;31m"          # Bad (red)
    SECTION="[1;33m"          # Section (yellow)
    NOTICE="[1;33m"           # Notice (yellow)
    OK="[1;32m"               # Ok (green)
    BAD="[1;31m"              # Bad (red)

    # Normal color names
    YELLOW="[1;33m"
    WHITE="[1;37m"
    GREEN="[1;32m"
    RED="[1;31m"
    PURPLE="[0;35m"
    MAGENTA="[1;35m"
    BROWN="[0;33m"
    CYAN="[0;36m"
    BLUE="[0;34m"
#
#################################################################################
#

#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen, CISOfy - https://cisofy.com
