#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2013, Michael Boelen
# Copyright 2013-2016, CISOfy
#
# Website  : https://cisofy.com
# Blog     : http://linux-audit.com
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Solaris
#
#################################################################################
#
    InsertSection "Solaris"
#
#################################################################################
#
    # Test        : SOL-xxxx
    # Description : Check if Stop-A is disabled
#    Register --test-no SOL-xxxx --weight L --network NO --category security --description "Check for running SSH daemon"
#    if [ ${SKIPTEST} -eq 0 ]; then
#       LogText "Test: Searching for a SSH daemon"
#       # Check running processes
#       FIND=`${PSBINARY} ax | ${GREPBINARY} "sshd" | ${GREPBINARY} -v "grep"`
#       if [ ! "${FIND}" = "" ]; then
#    SSH_DAEMON_RUNNING=1
#           LogText "Result: Stop-A is disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result "${STATUS_FOUND}" --color GREEN
#         else
#           LogText "Result: Stop-A is NOT disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result "${STATUS_NOT_FOUND}" --color WHITE
#       fi
#    fi
#
#################################################################################
#
    # Test        : SOL-xxxx
    # Description : Check if vold is disabled, to disallow unaudited mounts
#    Register --test-no SOL-xxxx --weight L --network NO --category security --description "Check for running SSH daemon"
#    if [ ${SKIPTEST} -eq 0 ]; then
#       LogText "Test: Searching for a SSH daemon"
#       # Check running processes
#       FIND=`${PSBINARY} ax | ${GREPBINARY} "sshd" | ${GREPBINARY} -v "grep"`
#       if [ ! "${FIND}" = "" ]; then
#           SSH_DAEMON_RUNNING=1
#           LogText "Result: Stop-A is disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result "${STATUS_FOUND}" --color GREEN
#         else
#           LogText "Result: Stop-A is NOT disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result "${STATUS_NOT_FOUND}" --color WHITE
#       fi
#    fi

#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
