#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen (michael@rootkit.nl), The Netherlands
# Web site: http://www.rootkit.nl
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
#    InsertSection "Hardening tools"
#
#################################################################################
#
    # Checking Solaris Security Toolkit (Jass)
    # Test        : HRDN-7402
    # Description : Check jass hardening
    #    Register --test-no HRDN-7402 --weight L --network NO --description "Check jass hardening"
    #    if [ ${SKIPTEST} -eq 0 ]; then
    #        if [ -d /opt/SUNWjass -o -d /var/opt/SUNWjass ]; then
    #        logtext "Result: found Solaris Security Toolkit (Jass hardening tool)"
    #    fi
    #
#
#################################################################################
#
    # Test        : HRDN-7410
    # Description : Check tiger hardening tool
#
#################################################################################
#
    # Test        : HRDN-7420
    # Description : Check Bastille Unix hardening tool
#
#################################################################################
#
    # Checking Solaris Security Toolkit (ASET)
    # - Automated Security Enhancement Tool

    # AddHP 3 3

#wait_for_keypress

#
#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen - www.rootkit.nl - The Netherlands
