#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen, CISOfy (michael.boelen@cisofy.com)
# Web site: https://cisofy.com
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Solaris
#
#################################################################################
#
    InsertSection "Solaris"
#
#################################################################################
#
    # Test        : SOL-xxxx
    # Description : Check if Stop-A is disabled
#    Register --test-no SOL-xxxx --weight L --network NO --description "Check for running SSH daemon"
#    if [ ${SKIPTEST} -eq 0 ]; then
#       logtext "Test: Searching for a SSH daemon"
#       # Check running processes
#       FIND=`${PSBINARY} ax | grep "sshd" | grep -v "grep"`
#       if [ ! "${FIND}" = "" ]; then
#    SSH_DAEMON_RUNNING=1
#           logtext "Result: Stop-A is disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result FOUND --color GREEN
#         else
#           logtext "Result: Stop-A is NOT disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result "NOT FOUND" --color WHITE
#       fi
#    fi
#
#################################################################################
#
    # Test        : SOL-xxxx
    # Description : Check if vold is disabled, to disallow unaudited mounts
#    Register --test-no SOL-xxxx --weight L --network NO --description "Check for running SSH daemon"
#    if [ ${SKIPTEST} -eq 0 ]; then
#       logtext "Test: Searching for a SSH daemon"
#       # Check running processes
#       FIND=`${PSBINARY} ax | grep "sshd" | grep -v "grep"`
#       if [ ! "${FIND}" = "" ]; then
#           SSH_DAEMON_RUNNING=1
#           logtext "Result: Stop-A is disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result FOUND --color GREEN
#         else
#           logtext "Result: Stop-A is NOT disabled"
#           Display --indent 2 --text "- Checking running SSH daemon" --result "NOT FOUND" --color WHITE
#       fi
#    fi

#
#################################################################################
#

wait_for_keypress

#
#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen, CISOfy - https://cisofy.com
