#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2013, Michael Boelen
# Copyright 2013-2016, CISOfy
#
# Website  : https://cisofy.com
# Blog     : http://linux-audit.com
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Virtualization
#
#################################################################################
#
    InsertSection "Virtualization"
#
#################################################################################
#
#    # Test        : VIRT-1920
#    # Description : Checking VMware
#    Register --test-no VIRT-1920 --weight L --network NO --category security --description "Checking VMware guest status"
#    if [ ${SKIPTEST} -eq 0 ]; then
#        # Initialise
#        VMWARE_GUEST=0
#        Display --indent 2 --text "- Checking VMware guest status"
#        # check memory driver file
#        # check LKM list
#        # check vmware tools
#        LogText "Test: checking VMware tools daemon presence"
#        if [ ! "${VMWARETOOLSBINARY}" = "" ]; then
#            LogText "Result: VMware tools binary found"
#            VMWARE_GUEST=1
#            Display --indent 4 --text "- Checking VMware tools daemon" --result "${STATUS_FOUND}" --color GREEN
#          else
#            Display --indent 4 --text "- Checking VMware tools daemon" --result "${STATUS_NOT_FOUND}" --color WHITE
#        fi
#
#    fi
#
#################################################################################
#

WaitForKeyPress

#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
