#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen (michael@rootkit.nl), The Netherlands
# Web site: http://www.rootkit.nl
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# TCP Wrappers
# Run after: NFS checks
#
#################################################################################
#
#
#################################################################################
#
#    InsertSection "TCP Wrappers"
#
#################################################################################
#
    # Test        : TCPW-xxxx (YYY move to nameservices section)
    # Description : Basic nameserver configuration tests (connectivity)
#    Register --test-no TCPW-xxxx --weight L --network YES --description "Basic nameserver configuration tests"
#    if [ ${SKIPTEST} -eq 0 ]; then
#        Display --indent 2 --text "- Checking configured nameservers"
#        logtext "Test: Checking /etc/resolv.conf file"
#		    	    Display --indent 8 --text "Nameserver: ${I}" --result OK --color GREEN
#		    	    ReportSuggestion ${TEST_NO} "Check connection to this nameserver and make sure no outbound DNS queries are blocked (port 53 UDP and TCP)."
#			    ReportWarning ${TEST_NO} "L" "Nameserver ${I} does not respond"
#    fi
#
#################################################################################
#

#wait_for_keypress

#
#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen - www.rootkit.nl - The Netherlands
