#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2013, Michael Boelen
# Copyright 2013-2016, CISOfy
#
# Website  : https://cisofy.com
# Blog     : http://linux-audit.com
# GitHub   : https://github.com/CISOfy/lynis
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Hints and Tips
#
#################################################################################
#

    # Only show tips when enabled
    if [ ${SHOW_TOOL_TIPS} -eq 1 ]; then

        # Bash completion support
        if [ ! "${ETC_PATHS}" = "" ]; then
            for I in ${ETC_PATHS}; do
                if [ -d ${I}/bash-completion.d ]; then
                    if [ ! -f ${ETC_PATHS}/bash_completion.d/lynis ]; then
                        Display "This system has a bash_completition directory. Copy extras/bash_completion.d/lynis to ${I} to get completion support for Lynis"
                    fi
                fi
            done
        fi
    fi


#
#================================================================================
# Lynis - Security Auditing and System Hardening for Linux and UNIX - https://cisofy.com
