#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2015, Michael Boelen, CISOfy (michael.boelen@cisofy.com)
# Web site: https://cisofy.com
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Hints and Tips
#
#################################################################################
#

    # Only show tips when enabled
    if [ ${SHOW_TOOL_TIPS} -eq 1 ]; then

        # Bash completion support
        if [ ! "${ETC_PATHS}" = "" ]; then
            for I in ${ETC_PATHS}; do
                if [ -d ${I}/bash-completion.d ]; then
                    if [ ! -f ${ETC_PATHS}/bash_completion.d/lynis ]; then
                        Display "This system has a bash_completition directory. Copy extras/bash_completion.d/lynis to ${I} to get completion support for Lynis"
                    fi
                fi
            done
        fi
    fi


#
#================================================================================
# Lynis - Copyright 2007-2015, Michael Boelen, CISOfy - https://cisofy.com
